
-- create table person
-- (
--    id integer not null,
--    name varchar(255) not null,
--    location varchar(255),
--    birth_date timestamp,
--    primary key(id)
-- );

/* Replace H2 sysdate() function(deprecated) with CURRENT_DATE() function */
-- INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE )
-- VALUES(10001,  'Ranga', 'Hyderabad',CURRENT_DATE());
-- INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE )
-- VALUES(10002,  'James', 'New York',CURRENT_DATE());
-- INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE )
-- VALUES(10003,  'Pieter', 'Amsterdam',CURRENT_DATE());

INSERT INTO COURSE (ID, NAME, CREATE_TIME, UPDATE_TIME)
VALUES (10001,'Science', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP);

INSERT INTO COURSE (ID, NAME,CREATE_TIME, UPDATE_TIME)
VALUES (10002,'Maths', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP);

INSERT INTO COURSE (ID, NAME, CREATE_TIME, UPDATE_TIME)
VALUES (10003,'Social Science', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP);


INSERT INTO PASSPORT (ID, NUMBER)
VALUES (40001,'A123456');
INSERT INTO PASSPORT (ID, NUMBER)
VALUES (40002,'B123456');
INSERT INTO PASSPORT (ID, NUMBER)
VALUES (40003,'C123456');

INSERT INTO STUDENT (ID, NAME, PASSPORT_ID)
VALUES (20001,'Ranga', 40001);
INSERT INTO STUDENT (ID, NAME, PASSPORT_ID)
VALUES (20002,'Adam', 40002);
INSERT INTO STUDENT (ID, NAME, PASSPORT_ID)
VALUES (20003,'Jane', 40003);

INSERT INTO REVIEW (ID, DESCRIPTION, RATING, COURSE_ID)
VALUES (40001,'good course', '4', 10001);
INSERT INTO REVIEW (ID, DESCRIPTION, RATING, COURSE_ID)
VALUES (40002,'best course', '4', 10001);
INSERT INTO REVIEW (ID, DESCRIPTION, RATING, COURSE_ID)
VALUES (40003,'nice explanation', '4', 10003);